### ISSUE TITLE
Create new Transaction when sending message out side of a transaction.

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/NServiceBus.ActiveMQ#4]
Raised by @remogloor
Migrated from by https://github.com/Particular/NServiceBus/issues/962

Sending a message within a transaction is much faster when using ActiveMQ in DTC mode. 

Therefore we should create a new TransactionScope when sending a message outside of a transaction.

**Comment by SimonCropp** [comment]
Raised by @SimonCropp

@emogloor any chance of getting a pull requests that illustrates how this would work?

**Comment by SimonCropp** [comment]
Raised by @danielmarbach

Hy simon,
This should be @remogloor :dancers:

**Comment by SimonCropp** [comment]
Raised by @SimonCropp

@danielmarbach  wow how did i screw that up. i always use the completion.

**Comment by remogloor** [comment]
If I remember correctly, the idea was to add a new TransactionScope(Required) to create a new Tx or attach to an existing one around 

"producer.Send(destinationEvaluator.GetDestination(session, destination, destinationPrefix), jmsMessage);" in MessageProducer Line 30 when DTC transactions are enabled.
