### ISSUE TITLE
ActiveMQ Transport consider upgrade 1.6

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/NServiceBus.ActiveMQ#5]
Raised by @danielmarbach
Migrated from by https://github.com/Particular/NServiceBus/issues/1475

There is a new version of the ActiveMQ client released under 1.6 which addresses several issues. The problem is that we are currently using a custom build of 1.5.6 but not all issues have been addressed by the ActiveMQ Team or only partially fix. There are actually to solution which we could try out:
1. Don't trust the ActiveMQ team, switch to 1.6 branch and reapply and check all custom added stuff by @remogloor
2. Partially trust ActiveMQ team, switch to 1.6, rerun everything including load testing in staging environment and only switch back to point 1 if necessary

The problem is that we have currently no priority by our customer to do either 1. or 2. Hopefully our NMS pain will grow so large that we can finally address those issues but I opened that issue anyway in case someone wants to do it.

**Comment by remogloor** [comment]
We are currently porting the changes to 1.6. Unfortunatly a lot changed so that it is not easy

**Comment by johnsimons** [comment]
@remogloor where is this repo that you guys are patching?
Should this repo exist under our organisation?

I really dislike this situation that we are in, it is not viable in the long run.

@udidahan and @andreasohlund 
What is our way forward?

**Comment by SimonCropp** [comment]
@remogloor i think john has a point. if we are deploying a custom build+branch of ActiveMQ client we should have a little more rigor around that process.
- where is the current branch
- what issues have been fixed in it
- how do we build it?
- links to the relevant issue/pull requests in the main ActiveMQ repo
- who has access to the repo, eg if i need to fix a bug in a hurry can i do so?
- licensing. who owns the code produced in this custom branch?

**Comment by danielmarbach** [comment]
Let's be absolutely clear: we also dislike this situation. But fact is there are major things such as failover handling and Dtc support broken. We did several contact request, provided patches, started discussions on the issue tracker... The maintainers don't care really and the driver is getting more and more a nightmare to manage.

**Comment by johnsimons** [comment]
Maybe we need to consider documenting these issues and not support failover
handling and DTC in the ActiveMQ transport.
If this was a closed source lib (like SqlServer, MSMQ or WebSphereMQ) we
would not have been able to fix these issues at all and we would still have
managed.

On 27 September 2013 14:27, danielmarbach notifications@github.com wrote:

> Let's be absolutely clear: we also dislike this situation. But fact is
> there are major things such as failover handling and Dtc support broken. We
> did several contact request, provided patches, started discussions on the
> issue tracker... The maintainers don't care really and the driver is
> getting more and more a nightmare to manage.
> 
> > Am 27.09.2013 um 01:28 schrieb John Simons notifications@github.com:
> > 
> > @remogloor where is this repo that you guys are patching?
> > Should this repo exist under our organisation?
> > 
> > I really dislike this situation that we are in, it is not viable in the
> > long run.
> > 
> > @udidahan and @andreasohlund
> > What is our way forward?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Particular/NServiceBus.ActiveMQ/issues/5#issuecomment-25222055
> .

## 

Regards
John Simons
NServiceBus

**Comment by danielmarbach** [comment]
You yes but not we. Because we need it in the project. Maybe we can go down again the path and doing political pressure game on the driver :)

> Am 27.09.2013 um 06:51 schrieb John Simons notifications@github.com:
> 
> Maybe we need to consider documenting these issues and not support failover 
> handling and DTC in the ActiveMQ transport. 
> If this was a closed source lib (like SqlServer, MSMQ or WebSphereMQ) we 
> would not have been able to fix these issues at all and we would still have 
> managed. 
>

**Comment by johnsimons** [comment]
I think the political pressure needs to come from us, I've raised this internally, let's see what happens.

**Comment by danielmarbach** [comment]
But I certainly agree that:

Need to open up the SVN repo or host the patched sources on GH

Or

Add remo to the maintainer list of the driver (don't know if possible)

Document the state of the nsb transport publicly so that people know

**Comment by danielmarbach** [comment]
Another option would be to buy Jim Gomes or Timothy Bish to obey :)
