### ISSUE TITLE
NServiceBusVersion header is hard coded to 4.0 in ActiveMq

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/NServiceBus.ActiveMQ#8]
Raised by @SimonCropp
Migrated from by https://github.com/Particular/NServiceBus/issues/1373

see here https://github.com/NServiceBus/NServiceBus/blob/master/src/ActiveMQ/NServiceBus.ActiveMQ/ActiveMqMessageMapper.cs#L99

```
if (!transportMessage.Headers.ContainsKey(Headers.NServiceBusVersion))
{
    transportMessage.Headers[Headers.NServiceBusVersion] = "4.0.0.0";
}
```

Is there a reason for this? If so the code should have a comment to reflect that since as the cdoe is now it looks like a bug

@remogloor  thoughts?

**Comment by remogloor** [comment]
This was added for interop with none NSB AMQ client. E.g. a Java client is sending a message to a NSB endpoint. 

At the time we implemented the AMQ transport NSB required the header. E.g. there were Message mutators to convert NSB 3.0/2.0 messages to 4.0. By adding the version 4.0 they are skipped.

I don't know if it is still nesesary or if there were changes to the core in the meantime.
